#!/usr/bin/perl

use strict;

use EBox::Global;
use EBox::MailListLdap;
use EBox::Sudo qw(:all);

EBox::init();

my $global = EBox::Global->getInstance(1);
my $mlists = new EBox::MailListLdap;

sub update {
	$mlists->{ldap}->ldapCon;
	my $ldap = $mlists->{ldap}->{ldap};
	my $dn = "ou=postfix, " . $vdomain->{ldap}->dn;

	my $dn = $alias->mailListDn();

	my $result = $ldap->add($dn, attr => [
		'ou'	=>	'mailalias',
		'objectClass' => 'top',
		'objectClass' => 'organizationalUnit'
	]);

	($result->is_error) and warn "Cant initialize mail alias leaf.";
}

sub clean {
	$vdomain->{ldap}->ldapCon;
	my $ldap = $vdomain->{ldap}->{ldap};
	my $pdn = "ou=postfix, " . $vdomain->{ldap}->dn;
	my $adn = $alias->aliasDn;
	my $vdn = $vdomain->vdomainDn;
	
	my @domains = $vdomain->vdomains;

	foreach (@domains) {
		$mlists->delAliasesFromVDomain($_);
	}
	
	my $result = $ldap->delete($adn);
	($result->is_error) and warn "Can not remove postfix leaf ".$result->error;
	$result = $ldap->delete($vdn);
	($result->is_error) and warn "Can not remove postfix leaf ".$result->error;
	$result = $ldap->delete($pdn);
	($result->is_error) and warn "Can not remove postfix parent leaf ".$result->error;
	
	root("/bin/rm -rf /var/vmail/*");
}

sub usage {
	print "Usage: $0 update | clean\n";
	exit 1;
}

unless ($#ARGV == 0) {
	usage();
}

if ($ARGV[0] eq 'update') {
	update();
} elsif ($ARGV[0] eq 'clean') {
	clean();
} else {
	usage();
}


